# Generated by Django 3.0.4 on 2020-05-10 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('x', models.DecimalField(decimal_places=6, max_digits=11)),
                ('y', models.DecimalField(decimal_places=6, max_digits=11)),
                ('address_line_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('vac', 'Vacation')], default='home', max_length=10)),
                ('district', models.CharField(choices=[('1', 'Central and Western'), ('2', 'Eastern'), ('3', 'Southern'), ('4', 'Wan Chai'), ('5', 'Sham Shui Po'), ('6', 'Kowloon City'), ('7', 'Kwun Tong'), ('8', 'Wong Tai Sin'), ('9', 'Yau Tsim Mong'), ('10', 'Islands'), ('11', 'Kwai Tsing'), ('12', 'North'), ('13', 'Sai Kung'), ('14', 'Sha Tin'), ('15', 'Tai Po'), ('16', 'Tsuen Wan'), ('17', 'Tuen Mun'), ('18', 'Yuen Long')], default='1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id_document_no', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('date_of_confirmation', models.DateField()),
                ('case_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VisitingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('case_no', models.CharField(max_length=20)),
                ('loc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.Location')),
            ],
        ),
    ]
