# Generated by Django 3.0.5 on 2020-04-06 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id_document_no', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('date_of_confirmation', models.DateField()),
                ('case_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Locations_visited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('x', models.DecimalField(decimal_places=6, max_digits=11)),
                ('y', models.DecimalField(decimal_places=6, max_digits=11)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('address_line_3', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('vac', 'Vacation')], default='home', max_length=10)),
                ('case_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patients')),
            ],
        ),
    ]
