# Generated by Django 3.0.4 on 2020-05-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitingrecord',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visitingrecord',
            name='start_date',
            field=models.DateField(),
        ),
    ]
