# Generated by Django 3.0.5 on 2020-04-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations_visited',
            name='address_line_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='locations_visited',
            name='address_line_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='locations_visited',
            name='address_line_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='locations_visited',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
