# Generated by Django 3.0.2 on 2020-05-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CHP'), (2, 'Epidemiologists')], default=1),
        ),
    ]
