# Generated by Django 3.0.6 on 2020-05-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.CharField(choices=[('1', 'Central and Western'), ('2', 'Eastern'), ('3', 'Southern'), ('4', 'Wan Chai'), ('5', 'Sham Shui Po'), ('6', 'Kowloon City'), ('7', 'Kwun Tong'), ('8', 'Wong Tai Sin'), ('9', 'Yau Tsim Mong'), ('10', 'Islands'), ('11', 'Kwai Tsing'), ('12', 'North'), ('13', 'Sai Kung'), ('14', 'Sha Tin'), ('15', 'Tai Po'), ('16', 'Tsuen Wan'), ('17', 'Tuen Mun'), ('18', 'Yuen Long')], default='1', max_length=20),
        ),
    ]
