# Generated by Django 3.0.6 on 2020-05-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200515_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitingrecord',
            name='detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
