# Generated by Django 3.0.5 on 2020-04-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200406_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations_visited',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
