# Generated by Django 3.0.6 on 2020-05-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_locations_visited_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations_visited',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='locations_visited',
            name='start_date',
        ),
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('case_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patients')),
                ('loc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Locations_visited')),
            ],
        ),
    ]
